# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0052_auto_20170324_1506'),
        ('pretixbase', '0052_auto_20170318_1748'),
    ]

    operations = [
    ]
